name: CD - Deploy/Release

on:
  workflow_run:
    workflows: ["CI - Verificação de Código"]
    types: [completed]
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Simulando Deploy
        run: echo "O código foi validado. Iniciando empacotamento e distribuição..."