name: Pipeline Academico com Alerta

on:
  push:
    branches: [ "main", "feature/ci-cd" ]

jobs:
  build:
    name: Build e Teste
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Instalando dependencias
        run: echo "Instalando pacotes..."

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Executando Deploy
        run: echo "Projeto implantado!"

  notificacao:
    name: Alerta Discord
    runs-on: ubuntu-latest
    needs: [build, deploy]
    if: always() # Garante que o alerta seja enviado mesmo se algo falhar
    steps:
      - name: Enviar Mensagem ao Discord
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DC_NOTI }}
          content: "🚀 **Novo Commit no Projeto Acadêmico!**\nUsuário: ${{ github.actor }}\nStatus: ${{ job.status }}"